### ISSUE TITLE
Error during Installation 

### ISSUE THREAD

**Issue by theoldbeginner** [dmdhrumilmistry/pyhtools#17]
Hey guys,

the following error was shown during installation.
What can I do to solve the issue?

Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error                                      
  × Preparing metadata (pyproject.toml) did not run successfully.            │ exit code: 1
  ╰─> [5 lines of output]                                                        running dist_info
      creating /tmp/pip-modern-metadata-0xlezuvo/pyinstaller.egg-info            writing manifest file '/tmp/pip-modern-metadata-0xlezuvo/pyinstaller.egg-info/SOURCES.txt'                                                            writing manifest file '/tmp/pip-modern-metadata-0xlezuvo/pyinstaller.egg-info/SOURCES.txt'                                                            error: [('/tmp/pip-modern-metadata-0xlezuvo/pyinstaller.egg-info/dependency_links.txt', '/tmp/pip-modern-metadata-0xlezuvo/pyinstaller.dist-info/dependency_links.txt', "[Errno 13] Permission denied: '/tmp/pip-modern-metadata-0xlezuvo/pyinstaller.dist-info/dependency_links.txt'"), ('/tmp/pip-modern-metadata-0xlezuvo/pyinstaller.egg-info/entry_points.txt', '/tmp/pip-modern-metadata-0xlezuvo/pyinstaller.dist-info/entry_points.txt', "[Errno 13] Permission denied: '/tmp/pip-modern-metadata-0xlezuvo/pyinstaller.dist-info/entry_points.txt'"), ('/tmp/pip-modern-metadata-0xlezuvo/pyinstaller.egg-info/top_level.txt', '/tmp/pip-modern-metadata-0xlezuvo/pyinstaller.dist-info/top_level.txt', "[Errno 13] Permission denied: '/tmp/pip-modern-metadata-0xlezuvo/pyinstaller.dist-info/top_level.txt'"), ('/tmp/pip-modern-metadata-0xlezuvo/pyinstaller.egg-info', '/tmp/pip-modern-metadata-0xlezuvo/pyinstaller.dist-info', "[Errno 13] Permission denied: '/tmp/pip-modern-metadata-0xlezuvo/pyinstaller.dist-info'")]                                               [end of output]
                                                                             note: This error originates from a subprocess, and is likely not a problem with pip.                                                                error: metadata-generation-failed                                                                                                                     × Encountered error while generating package metadata.                     ╰─> See above for output.                                                                                                                             note: This is an issue with the package mentioned above, not pip.          hint: See above for details.

**Comment by theoldbeginner** [comment]
Dear guy/s,
first things first: Lot of thanks for your fast answer.
The sudo command was the breakthrough!
Best wishes!

**Comment by dmdhrumilmistry** [comment]
> Dear guy/s, first things first: Lot of thanks for your fast answer. The sudo command was the breakthrough! Best wishes!

@theoldbeginner I'm glad it helped!
I'm closing this issue right now. In future if you face any issues, you can get help from the community or create an issue
