### ISSUE TITLE
python3 -m pyhtools report error

### ISSUE THREAD

**Issue by xiaoyuer0408** [dmdhrumilmistry/pyhtools#65]
shiyue@shiyue:~/pyhtools$ python3 -m pyhtools
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/shiyue/pyhtools/pyhtools/__main__.py", line 1, in <module>
    from . UI import functions as UI
  File "/home/shiyue/pyhtools/pyhtools/UI/functions.py", line 4, in <module>
    from pyhtools.evil_files.malwares.utils import send_mail
ModuleNotFoundError: No module named 'pyhtools.evil_files'

How to solve the error reported here, I have tried many times

**Comment by dmdhrumilmistry** [comment]
> shiyue@shiyue:~/pyhtools$ python3 -m pyhtools Traceback (most recent call last): File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main return _run_code(code, main_globals, None, File "/usr/lib/python3.10/runpy.py", line 86, in _run_code exec(code, run_globals) File "/home/shiyue/pyhtools/pyhtools/**main**.py", line 1, in from . UI import functions as UI File "/home/shiyue/pyhtools/pyhtools/UI/functions.py", line 4, in from pyhtools.evil_files.malwares.utils import send_mail ModuleNotFoundError: No module named 'pyhtools.evil_files'
> 
> How to solve the error reported here, I have tried many times

@xiaoyuer0408 thanks for reporting this issue. This issue is due to changes I made in order to comply with pypi policies.

I've moved all evil files to [pyhtools-evil-files](https://github.com/dmdhrumilmistry/pyhtools-evil-files) repo. Will fix this issue ASAP.

**Comment by xiaoyuer0408** [comment]
ok sir, i sent you an e-mail and hope you can reply me

**Comment by dmdhrumilmistry** [comment]
> ok sir, i sent you an e-mail and hope you can reply me

@xiaoyuer0408 I haven't received any mail.

You can fix this issue by running the below command:

```bash
python3 -m pip install git+https://github.com/dmdhrumilmistry/pyhtools-evil-files.git
```
